Cargo.toml: relax kvm-bindings version requirement
Our dep kvm-ioctls 0.11.0 requires kvm-bindings >= 0.5.0.
kvm-bindings 0.6.0 was recently released. This leads cargo to
pull in both 0.5.0 and 0.6.0 kvm-bindings version, which then
breaks our build with:

error[E0308]: mismatched types
  --> tests/snp_launch.rs:41:38
   |
41 |         vm_fd.set_user_memory_region(mem_region).unwrap();
   |               ---------------------- ^^^^^^^^^^ expected struct `kvm_bindings::x86::bindings::kvm_userspace_memory_region`, found struct `kvm_userspace_memory_region`
   |               |
   |               arguments to this function are incorrect
   |
   = note: perhaps two different versions of crate `kvm_bindings` are being used?

Relax our kvm-bindings version to check to match kvm-ioctls, which
seems to avoid the issue.

Signed-off-by: Cole Robinson <crobinso@redhat.com>